# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-sap
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  title: terraform-google-sap for SAP HANA Scaleout
  source:
    repo: https://github.com/terraform-google-modules/terraform-google-sap.git
    sourceType: git
  version: 1.1.2
  actuationTool:
    type: Terraform
    version: '>=0.12.6'
  examples:
  - name: sap_hana_ha_simple
    location: examples/sap_hana_ha_simple
  - name: sap_hana_scaleout_simple
    location: examples/sap_hana_scaleout_simple
  - name: sap_hana_simple
    location: examples/sap_hana_simple
  variables:
  - name: can_ip_forward
    description: Whether sending and receiving of packets with non-matching source or destination IPs is allowed.
    type: bool
    default: true
    required: false
  - name: instance_name
    description: Hostname of the GCE instance.
    type: string
    required: true
  - name: linux_image
    description: Linux image name to use.
    type: string
    required: true
  - name: linux_image_project
    description: The project which the Linux image belongs to.
    type: string
    required: true
  - name: machine_type
    description: Machine type for the instances.
    type: string
    required: true
  - name: network_tags
    description: OPTIONAL - Network tags can be associated to your instance on deployment. This can be used for firewalling or routing purposes.
    type: list(string)
    default: []
    required: false
  - name: post_deployment_script
    description: OPTIONAL - gs:// or https:// location of a script to execute on the created VM's post deployment.
    type: string
    default: ""
    required: false
  - name: primary_startup_url
    description: Startup script to be executed when the VM boots, should not be overridden.
    type: string
    default: curl -s BUILD.TERRA_SH_URL/sap_hana_scaleout/startup.sh | bash -s BUILD.TERRA_SH_URL
    required: false
  - name: project_id
    description: Project id where the instances will be created.
    type: string
    required: true
  - name: public_ip
    description: OPTIONAL - Defines whether a public IP address should be added to your VM. By default this is set to Yes. Note that if you set this to No without appropriate network nat and tags in place, there will be no route to the internet and thus the installation will fail.
    type: bool
    default: true
    required: false
  - name: reservation_name
    description: |
      Use a reservation specified by RESERVATION_NAME.
      By default ANY_RESERVATION is used when this variable is empty.
      In order for a reservation to be used it must be created with the
      "Select specific reservation" selected (specificReservationRequired set to true)
      Be sure to create your reservation with the correct Min CPU Platform for the
      following instance types:
      n1-highmem-32 : Intel Broadwell
      n1-highmem-64 : Intel Broadwell
      n1-highmem-96 : Intel Skylake
      n1-megamem-96 : Intel Skylake
      m1-megamem-96 : Intel Skylake
      All other instance types can have automatic Min CPU Platform"
    type: string
    default: ""
    required: false
  - name: sap_deployment_debug
    description: OPTIONAL - If this value is set to true, the deployment will generates verbose deployment logs. Only turn this setting on if a Google support engineer asks you to enable debugging.
    type: bool
    default: false
    required: false
  - name: sap_hana_backup_nfs
    description: Google Filestore share for /hanabackup
    type: string
    required: true
  - name: sap_hana_deployment_bucket
    description: The GCS bucket containing the SAP HANA media. If this is not defined, the GCE instance will be provisioned without SAP HANA installed.
    type: string
    default: ""
    required: false
  - name: sap_hana_instance_number
    description: The SAP instance number. If this is not defined, the GCE instance will be provisioned without SAP HANA installed.
    type: number
    default: 0
    required: false
  - name: sap_hana_shared_nfs
    description: Google Filestore share for /hana/shared
    type: string
    required: true
  - name: sap_hana_sid
    description: The SAP HANA SID. SID must adhere to SAP standard (Three letters or numbers and start with a letter)
    type: string
    required: true
  - name: sap_hana_sidadm_password
    description: The linux sidadm login password. If this is not defined, the GCE instance will be provisioned without SAP HANA installed. Minimum requirement is 8 characters.
    type: string
    default: ""
    required: false
  - name: sap_hana_sidadm_password_secret
    description: The secret key used to retrieve the linux sidadm login from Secret Manager (https://cloud.google.com/secret-manager). The Secret Manager password will overwrite the clear text password from sap_hana_sidadm_password if both are set.
    type: string
    default: ""
    required: false
  - name: sap_hana_sidadm_uid
    description: The Linux UID of the <SID>adm user. By default this is set to 900 to avoid conflicting with other OS users.
    type: number
    default: 900
    required: false
  - name: sap_hana_standby_nodes
    description: Number of standby nodes to create.
    type: number
    default: 1
    required: false
  - name: sap_hana_system_password
    description: The SAP HANA SYSTEM password. If this is not defined, the GCE instance will be provisioned without SAP HANA installed. Minimum requirement is 8 characters with at least 1 number.
    type: string
    default: ""
    required: false
  - name: sap_hana_system_password_secret
    description: The secret key used to retrieve the SAP HANA SYSTEM login from Secret Manager (https://cloud.google.com/secret-manager). The Secret Manager password will overwrite the clear text password from sap_hana_system_password if both are set.
    type: string
    default: ""
    required: false
  - name: sap_hana_worker_nodes
    description: |
      Number of worker nodes to create.
      This is in addition to the primary node.
    type: number
    default: 1
    required: false
  - name: secondary_startup_url
    description: DO NOT USE
    type: string
    default: curl -s BUILD.TERRA_SH_URL/sap_hana_scaleout/startup_secondary.sh | bash -s BUILD.TERRA_SH_URL
    required: false
  - name: service_account
    description: OPTIONAL - Ability to define a custom service account instead of using the default project service account.
    type: string
    default: ""
    required: false
  - name: subnetwork
    description: The sub network to deploy the instance in.
    type: string
    required: true
  - name: zone
    description: Zone where the instances will be created.
    type: string
    required: true
  outputs:
  - name: hana_scaleout_standby_self_links
    description: List of self-links for the hana scaleout standbys created
  - name: hana_scaleout_worker_self_links
    description: List of self-links for the hana scaleout workers created
  - name: sap_hana_primary_self_link
    description: Self-link for the primary SAP HANA Scalout instance created.
  roles:
  - level: Project
    roles:
    - roles/owner
  services:
  - cloudresourcemanager.googleapis.com
  - storage-api.googleapis.com
  - serviceusage.googleapis.com
  - compute.googleapis.com
